name: Daily Twitter Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # 8:00 UTC daily
  workflow_dispatch:      # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape.py

      - name: Commit results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add tweets.csv
          git commit -m "Update scraped tweets $(date)" || echo "No changes"
          git push
